### ISSUE TITLE
undefined method `content_for' when app name contains a digit (?)

### ISSUE THREAD

**Issue by katafrakt** [hanami/hanami-2-application-template#22]
Steps to reproduce:

1. Clone this repo
2. `bin/install hanami_2_test`
3. `script/setup docker` (but happens on local setup too)
4. Go to localhost:3000

Result:

```
Puma caught this error: undefined method `content_for' for #<Hanami::View::Scope _name=nil _locals={} _render_env=#<Hanami::View::RenderEnvironment renderer=#<Hanami::View::Renderer paths=[#<Hanami::View::Path dir=#<Pathname:/app/slices/main/web/templates/layouts/application> root=#<Pathname:/app/slices/main/web/templates>>] format=:html engine_mapping={} options={:default_encoding=>"utf-8"}> inflector=#<Dry::Inflector> context=#<Hanami::View::Context _options={}> scope_builder=#<Hanami::View::ScopeBuilder namespace=nil> part_builder=#<Hanami::View::PartBuilder namespace=Main::View::Parts>>> (NoMethodError)
/usr/local/bundle/gems/hanami-view-2.0.0.alpha2/lib/hanami/view/scope.rb:160:in `method_missing'
/app/slices/main/web/templates/layouts/application.html.slim:6:in `__tilt_7340'
/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
/usr/local/bundle/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
/usr/local/bundle/gems/hanami-view-2.0.0.alpha2/lib/hanami/view/renderer.rb:49:in `render'
/usr/local/bundle/gems/hanami-view-2.0.0.alpha2/lib/hanami/view/renderer.rb:32:in `template'
/usr/local/bundle/gems/hanami-view-2.0.0.alpha2/lib/hanami/view/render_environment.rb:44:in `template'
/usr/local/bundle/gems/hanami-view-2.0.0.alpha2/lib/hanami/view/standalone_view.rb:354:in `call'
/usr/local/bundle/gems/hanami-controller-2.0.0.alpha2/lib/hanami/action/response.rb:79:in `render'
/usr/local/bundle/gems/hanami-controller-2.0.0.alpha2/lib/hanami/action/application_action.rb:90:in `handle'
/usr/local/bundle/gems/hanami-controller-2.0.0.alpha2/lib/hanami/action/standalone_action.rb:310:in `block in call'
/usr/local/bundle/gems/hanami-controller-2.0.0.alpha2/lib/hanami/action/standalone_action.rb:296:in `catch'
/usr/local/bundle/gems/hanami-controller-2.0.0.alpha2/lib/hanami/action/standalone_action.rb:296:in `call'
/usr/local/bundle/gems/hanami-router-2.0.0.alpha5/lib/hanami/router.rb:104:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/bundle/gems/dry-monitor-0.4.0/lib/dry/monitor/rack/middleware.rb:37:in `block in call'
/usr/local/bundle/gems/dry-monitor-0.4.0/lib/dry/monitor/notifications.rb:11:in `measure'
/usr/local/bundle/gems/dry-monitor-0.4.0/lib/dry/monitor/rack/middleware.rb:37:in `call'
/usr/local/bundle/gems/hanami-2.0.0.alpha2/lib/hanami/application.rb:362:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/usr/local/bundle/gems/rack-2.2.3/lib/rack/static.rb:161:in `call'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/configuration.rb:228:in `call'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:713:in `handle_request'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:472:in `process_client'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/server.rb:328:in `block in run'
/usr/local/bundle/gems/puma-4.3.7/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Now, this was bugging me since yesterday until I discovered that if I'm renaming the app to a name without `2` (i.e. `bin/install hanami_test`) - it works! Is it just some super weird edge case or an actual bug?

**Comment by solnic** [comment]
Yes it is a weird edge case. Props if somebody can debug this and explain what happens :D

**Comment by copiousfreetime** [comment]
I dug into this a bit - pretty sure its an inflector problem combined with zeitwerk.

I made 3 test projects

* `./bin/install fixing_test` -> worked as expected
* `./bin/install fixing_22_test` -> errored out on content_for
* `./bin/install fixing22_test` -> worked as expected

Doing some inflection tests:

```
fixing22_test[development]> i = Hanami.application[:inflector]
fixing22_test[development]> cname = i.classify('fixing_22_test')
=> "Fixing22Test"
fixing22_test[development]> p = i.underscore("Fixing22Test")
=> "fixing22_test"
```

So project name with underscore prefixing a number is not roundtripable through the `Dry::Inflector`

This looks like it results in the view context for the action not getting loaded correctly.

I changed `slices/main/lib/main/actions/home/show.rb` to have:
```ruby
def call(params)
  puts "I'm in #{self.class} and my view context is #{@view_context.inspect}"
  super
end
```

In the `fixing_22_test` this results in: 
```
I'm in Main::Actions::Home::Show and my view context is nil
```

In the `fixing22_test' this results in:
```
I'm in Main::Actions::Home::Show and my view context is #<Fixing22Test::View::Context _options={:content=>{}, :inflector=>#<Dry::Inflector>}>
```

I'm going to assume that the problem lies in the autoloading of an action's view. I don't know enough about Hanami's internals to know exactly where this is. I'll poke around a bit more and see what I can find. Hopefully this is enough clues for @solnic or someone to know exactly where the problem lies.

**Comment by copiousfreetime** [comment]
A later update. This all boils down to [`Hanami::Application.application_name`](https://github.com/hanami/hanami/blob/32d742f2379a847d6683fe5661b8dda5a7d054eb/lib/hanami/application.rb#L194-L196) 
```ruby

      def namespace
        inflector.constantize(name.split(MODULE_DELIMITER)[0..-2].join(MODULE_DELIMITER))
      end

      def application_name
        inflector.underscore(namespace).to_sym
      end
```
using `underscore` on the class name to get the `application_name` which is then used as the component namespace for the autoloader. 

This comes into conflict in [`Dry::System::ComponentsDir#component_for_path`](https://github.com/dry-rb/dry-system/blob/d27d6446a2724ce9122fc112fb084117aebf993c/lib/dry/system/component_dir.rb#L64-L79) when the `default_namespace` does not match the first portion of the path. The path would be `fixing_22_test` and the `default_namespace` would be `fixing22_test` and therefore the identifier would not be dequalified.

```ruby
      def component_for_path(path)
        separator = container.config.namespace_separator

        key = Pathname(path).relative_path_from(full_path).to_s
          .sub(RB_EXT, EMPTY_STRING)
          .scan(WORD_REGEX)
          .join(separator)

        identifier = Identifier.new(key, separator: separator)

        if identifier.start_with?(default_namespace)
          identifier = identifier.dequalified(default_namespace, namespace: default_namespace)
        end

        build_component(identifier, path)
      end
```

To test if explicitly setting the `Hanami::Application.application_name` would actually fix this, in my `fixing_22_test` project (`config/application.rb`) I just added an `application_name` method - and this fixed the `content_for` error.

```ruby
module Fixing22Test
  class Application < Hanami::Application

   # removed all the other boilerplate

    def self.application_name
      "fixing_22_test"
    end
  end
end
```

I'm not sure what the proper solution is - I can see a couple different options/issues

* when running `./bin/install` it does a round trip using the inflector and see if the project name argument will round trip - and if it doesn't either drop an error, or maybe be nice and add an `application_name` method to the `Application` class.
* at a higher level in hanami-cli or somewhere will need to be done to make sure that the project name can round trip and there's no conflict with the file system paths and the application name.

I hope this helps.

**Comment by katafrakt** [comment]
Wow, awesome job @copiousfreetime! I did some digging myself but never got this far.

**Comment by solnic** [comment]
oh wow thanks for digging into this. Now it seems like it's a legit bug in dry-system.

@timriley have you ever considered namespaces with digits? 😓 I think we just should not allow that, it's weird to have numbers in constants

**Comment by timriley** [comment]
I'll take a look at this and see what we can do, thank you for the amazing diagnostic work so far!

**Comment by katafrakt** [comment]
Seems to no longer be an issue (cannot reproduce).
