### ISSUE TITLE
Can't run setup/server because AppName::Routes doesn't exist

### ISSUE THREAD

**Issue by choallin** [hanami/hanami-2-application-template#35]
Aftere cloning this repo I run the bin/install command and everything worked fine.

Now, when I want to run the script/setup or the script/server scripts I get this error:

> /.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/dry-inflector-0.2.1/lib/dry/inflector.rb:89:in `const_get': uninitialized constant CourtManager::Routes (NameError)

**Comment by choallin** [comment]
The pr #33 fixes this issue

**Comment by waiting-for-dev** [comment]
Thanks for reporting. It's fixed now on main, as #33 has been merged.
