### ISSUE TITLE
Problem with installation instructions

### ISSUE THREAD

**Issue by katafrakt** [hanami/hanami-2-application-template#40]
This is a very minor thing, but perhaps worth fixing. The README says that one should run `./bin/install name_of_your_app` to get the template running. However, what actually happens is a bunch of errors:

```
./bin/install: line 1: require: command not found
./bin/install: line 2: require: command not found
./bin/install: line 3: require: command not found
./bin/install: line 4: require: command not found
./bin/install: line 5: require: command not found
./bin/install: line 7: class: command not found
./bin/install: line 180: warning: here-document at line 8 delimited by end-of-file (wanted `self')
./bin/install: line 8: class: command not found
```

It seems that either the `install` script should contain a shebang for Ruby or it should be run via `ruby /bin/install name_of_your_app` (both work).

**Comment by solnic** [comment]
Yeah it should just contain a shebang for Ruby
